name: Android CI

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Lint check
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: ./gradlew lint

      - name: Build
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: ./gradlew assemble